language: go
dist: bionic
go:
  - '1.12.x'

env:
  - GO111MODULE=on

stages:
  - name: test
  - name: release
    if: tag IS present

go_import_path: github.com/src-d/k8s-pod-headless-service-operator

jobs:
  include:
    - name: 'Unit tests'
      stage: test
      script: make test
    - name: 'Push image to Docker Hub'
      stage: release
      script:
        - PKG_OS=linux make packages
        - DOCKER_PUSH_LATEST=true make docker-push
    - name: 'Push image to Dispatch'
      stage: release
      script:
        - PKG_OS=linux make packages
        - make docker-build
        - docker tag maartje/nokiaremote:$TRAVIS_TAG dispatch.sh/maartje/nokiaremote
        - echo $DISPATCH_PASSWORD | docker login -u registry --password-stdin registry.dispatch.sh
        - docker push dispatch.sh/maartje/nokiaremote

